### ISSUE TITLE
How to disable telemetry with docker?

### ISSUE THREAD

**Issue by gerroon** [mickael-kerjean/nuage#100]
Hi 

The documentation does not mention how to remove the telemetry. This should be opt in now opt out because by the time one runs it , it already sent most of the info.

**Comment by mickael-kerjean** [comment]
Hello,

> The documentation does not mention how to remove the telemetry.

It is [here](https://github.com/mickael-kerjean/nuage/wiki/Customisation#user-content-usage-statistics). With docker the file is located in `/app/data/config/config.json`. To change it you can either:
- mount the [config.json](https://github.com/mickael-kerjean/nuage/blob/master/config/config.json) from your host to your container (with a volume pointing to `/app/data/config/config.json`)
- change it in your container by connecting to your container and run: `sed 's|"telemetry".*|"telemetry": false,|g' /app/data/config/config.json`

> by the time one runs it , it already sent most of the info

Nope, it sends information once the server is responding to a query coming from a browser.

> This should be opt in now opt out

I understand your point. However from my perspective, telemetry gives me both:
- confirmation that's nuage is worth installation on someone hardware which is a strong signal I don't lose my time doing something nobody cares about. I got way too many hobbies to lose time on worthless projects.
- a way to improve nuage both in term of bugs and performance

If we're honest just 1 minute, nobody would enable telemetry if that's an opt in feature hence me dropping the project considering the lack of signal. The funny part about analytics is nobody cared about it until this was documented and configurable but nobody spent the time to make a pull request to change the dependency on [google font](https://github.com/mickael-kerjean/nuage/blob/31f8c273ff40e9174e36a4025497a520d7cb58ca/client/assets/css/reset.scss#L1).

**Comment by gerroon** [comment]
Hi

Thanks for the info. I will see try it.


I can`t  speak for others , but if I knew that there was analytics when I installed it, I would not have installed it at all. it is my fault I should have read the docs properly before going forward.

As far as people started caring about the issue after you documented it, it makes sense people cant worry about issues they do not know about. Even if you did not mention it I would have found about it later. I have a restricted firewall and constrained dns queries, it would have shown up on my logs eventually. Generally that is how I personally run apps. 

It is impossible to know the real intentions of the developers by just looking at documentation or reading what they say about their own apps. I  am not a dev so I either have to rely on the developer's honesty or my firewall logs.

**Comment by mickael-kerjean** [comment]
> I can`t speak for others , but if I knew that there was analytics when I installed it, I would not have installed it at all.

That's everyone's choice, it can be opt out by editing a file, the how is already documented. The issue here is the fewer people report any analytics and the less update the project will receive in the long run. Time is the most precious thing I have and I don't mean to waste it on something worthless.

> I have a restricted firewall and constrained dns queries, it would have shown up in my logs eventually.

I've open an issue about this, I just don't have an interest in spending time to fix it as I'd rather bring more features to nuage. To refer to your firewall, unless you're a privacy extremist blocking everything coming from google your firewall wouldn't have catch it.

> know the real intentions of the developers by just looking at documentation or reading what they say about their own apps

I fully agree and being open source is an open invitation for anyone to perform an audit and contribute in making the project better. 

> I am not a dev .... If your only intention was  .... wiretrapping .... I am not accusing you of anythin ... this is creepy

The power of open source isn't free as in I didn't pay anything and got free support but in freedom of the user, take this freedom and use it for the good of everyone by making your ideas a reality and pushing the changes for everyone to use. Nuage isn't develop by a big corporation, it's just a week end project where contributions are encouraged. You mentionned not being a dev but I have no plan to spend my time on things I don't judge worthy of.
