### ISSUE TITLE
/nuage                                                                                                                                                     ⏎ ./nuage: error while loading shared libraries: libraw.so.19: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by gerroon** [mickael-kerjean/nuage#101]
Debian testing x64, I am  not exactly sure which library is missing here, I seem to have all the libraw libs I could install. 

I am using this release
https://github.com/mickael-kerjean/nuage/releases/download/v0.3/nuage.tar.gz

**Comment by mickael-kerjean** [comment]
Nuage needs a few C libraries to process images:
- libraw: to process RAW images coming from DSLR
- libvips: to resize images and optimise them for display on the browser

The message you got is nuage yelling that it can't find one of those shared library that are usually installed in your operation system in: `/usr/lib/`. To fix this you got two options:
- install libraw and libvips manually
- use the docker image that already have all the required dependencies

Long term I was planning to embed those library in the generated binary but it's not as simple as it seems.

**Comment by mickael-kerjean** [comment]
Hello again,

> I personally prefer that those libs are embedded

Yes me too despite the big debate in the linux community about the topic.

> I can compile and install those libs but sometimes doing that breaks the integrity of Debian distro

In this specific case, it won't.

> In anycase you might want to mention the library requirements in your docs.

For non patreons, until I can create a statically linked build, the only [supported installation method](https://github.com/mickael-kerjean/nuage/wiki/Installation:-Selfhosting) is docker.
The reason is the project doesn't have any other maintainers than me yet and I'd rather invest my time in creating new features and fix problems than creating and maintaining installers on a variety of platform.

> I assumed that the libs were statically linked

This is a priority for this project. Unfortunatly I'm not an expert in the domain and already spent countless hours trying to make it work without success. The road block came from trying to statically compile libvips that rely on the glib, tried many approach including musl but it doesn't work yet. I'd gladly get help from someone with experience on this topic.
