### ISSUE TITLE
local file support

### ISSUE THREAD

**Issue by ytzelf** [mickael-kerjean/nuage#103]
I browsed through the readme and saw nowhere support for local files. Is that a feature or in the works? 

Thanks!

**Comment by mickael-kerjean** [comment]
> I browsed through the readme and saw nowhere support for local files

That's because there's no support for it. From my perspective, the solution of accessing local file is a no brainer as every SSH server contains a SFTP component enable by default. Essentially, to access file, simply connect via SFTP on your localhost from nuage.

In the future, I have no plan to bring true local file as it would mean reinventing the wheel with all sort of problems that are very user specific like: user management, access management, quota management, encryption, ..... As of today, there's an awesome ecosystem of software available to solve all those problems and nuage goal is to integrate with them, not attempt to replace them.

For example: 
- http://files.kerjean.me is integrated with a ProFTPd server and LDAP which works amazingly well. User management is done via PAM/LDAP, access management is plain linux permissions coming from the LDAP directory and quota management is an existing ProFTPd module.
- a company I've been working for is integrating nuage with their own system that has integration with SAML and a bunch of weird thing that are very specific to their use case.

> Is that a feature or in the works?

The main feature in the work today is a [proper sharing feature](https://github.com/mickael-kerjean/nuage/commits/feature/share).

**Comment by ytzelf** [comment]
Thanks that's helpful. I'll think about an integration w/ minio
