### ISSUE TITLE
SFTP: "Unknown path" error for any path

### ISSUE THREAD

**Issue by Vaviloff** [mickael-kerjean/nuage#53]
Hi, this seems like a great project! Could you look into an sftp issue or direct me to where should I do digging?

Environment: Windows 7 x64
Node.js v8.6.0
Nuage: git cloned on 2018-05-08
Remote server: Ubuntu 14.04.3 in LAN (192.168.0.102)

After successfully connecting to server via `sftp` the error is shown:

> Oops!
> It seems this directory doesn't exist
> {"message":"Unknown Path"}

     info: GET /api/files/ls?path=%2F 404 2ms res=undefined, req=undefined, responseTime=2, host=127.0.0.1, protocol=http, method=GET, pathname=/api/files/ls?path=%2F, ip=::ffff:127.0.0.1, referrer=http://127.0.0.1:8334/files/, status=404

This happens even if `path` is set to user's home directory in advanced settings upon login.
I tried to debug it a bit and it seems that path always falls back to "\\" for some reason.

**Comment by mickael-kerjean** [comment]
Hi there, 
thank you for the report, I have to admit I can't replicate it as I don't have access to a window environment now. 
My gut feeling is the error is thrown [here](https://github.com/mickael-kerjean/nuage/blob/6a7ee63c0b4d76435966d10a63fe15b797f9f55e/server/ctrl/files.js#L28) because the [path variable is falsy](https://github.com/mickael-kerjean/nuage/blob/6a7ee63c0b4d76435966d10a63fe15b797f9f55e/server/ctrl/files.js#L21-L22) due to [this function](https://github.com/mickael-kerjean/nuage/blob/6a7ee63c0b4d76435966d10a63fe15b797f9f55e/server/ctrl/files.js#L136-L138) not working as expected on windows which is likely a "/" vs "\" issue.

**Comment by mickael-kerjean** [comment]
That's just gut feeling but i feel the issue comes from:
```javascript
function pathBuilder(req){
    return path.join(req.cookies.auth.payload.path || '', decodeURIComponent(req.query.path) || '');
}
```

req.cookies.auth.payload.path comes from your cookie which gives kind of a fake chroot and req.query.path is the actual path you're trying to access which in your case is "%2F" aka "/" once you decode it

**Comment by Vaviloff** [comment]
Mickael, thanks for quick answer! You're absolutely right, that was it.

If `pathBuilder` received such arguments:
>req.cookies.auth.payload.path: /home/www
>req.query.path: /

then on Windows `path.join` would turn them into this path:

> \home\www\\
which of course doesn't exist in Linux.

So just crudely joining starting and current path works for my use case (sFTP only),  but I wonder what is the correct way to do it?

**Comment by mickael-kerjean** [comment]
I see 2 possibilities:
1. Ditch the path library and write one that work for our use case
2. Try to configure the path library to make it behave correctly

I'm looking into the second option now and if it becomes too much of pain in the butt, will look at option 1

**Comment by mickael-kerjean** [comment]
I managed to put my hands on a windows laptop, this should fix your issue. Feel free to reopen if there's still someting wrong or create a new ticket if you find out about anything else
