### ISSUE TITLE
Some secret input fields are type=text instead of type=password 

### ISSUE THREAD

**Issue by mm-pagely** [mickael-kerjean/nuage#58]
* Git (password):

![image](https://user-images.githubusercontent.com/20521636/39950639-746330ea-5537-11e8-93c1-094b2a2d23bf.png)

* S3 (secret access key):

![image](https://user-images.githubusercontent.com/20521636/39950627-631f60a6-5537-11e8-96ad-fbed91988de0.png)

**Comment by mickael-kerjean** [comment]
2 things here:
- S3: my mistake
- Git: I've ran into some issues when it comes to the type=password thinghy. If the password has multiple line (like when you copy and paste a private key), the line returns would be eaten and the connection wouldn't establish. Unfortunatly browsers don't have a textarea version of the input type=password. The only workaround I found was to use the "-webkit-text-security" CSS property that makes it behave as an input type=password but unfortunatly it only works on webkit based browser. 

Any suggestion regarding Git?

**Comment by mickael-kerjean** [comment]
The S3 secret key id is now a proper password input. 

When it comes to git, I'm not sure anything else can be done (assuming the password can be a private key)

**Comment by mickael-kerjean** [comment]
I assume by the lack of response you don't have suggestions. I'm closing the ticket but feel free to comment if you have any suggestion and we'll reopen

**Comment by mickael-kerjean** [comment]
Problem: textarea needs to be used as a input[type="password"] to handle private key gracefully. That's why `-webkit-text-security: disc;` was created but unfortunatly it's not cross platform. I found out about https://github.com/noppa/text-security, the idea is quite clever, it relies on a special font that only include the disc character.
Problem solve

**Comment by hughbris** [comment]
Did your commit for S3 get reverted @mickael-kerjean ?

I am using the latest Docker image and my S3 input is marked up like:

```html
<input class="component_input" name="secret_access_key" type="text" placeholder="Secret Access Key*" autocomplete="new-password" autocorrect="off" autocapitalize="none" spellcheck="false" value="">
```
Definitely not a password input.

BTW why is the autocomplete attribute set to `new-password` here? I'd never heard of this one but apparently it prevents recalling any value. I know my client will not be happy having to paste in a long access key secret every time but I don't want to store it on the server. I was hoping to rely on their browser's password autocompleter. It's a big part of getting their buy-in for secure cloud storage.

If I knew Go I might offer you a PR or hack my own fork. Sorry I don't.

**Comment by mickael-kerjean** [comment]
It's not that easy. Filestash has an internal library used to generate forms via a custom made DSL. That form generator is used in a few places like the login page from which you made that screenshot but also the admin console and the form file type which enable stuff like [this](https://demo.filestash.app/login?type=ldap&next=/view/cn%3Dusers/uid%3Dadmin.form&hostname=ldap%3A%2F%2Fipa.demo1.freeipa.org&bind_dn=uid%3Dadmin%2Ccn%3Dusers%2Ccn%3Daccounts%2Cdc%3Ddemo1%2Cdc%3Dfreeipa%2Cdc%3Dorg&bind_password=Secret123&base_dn=cn%3Daccounts%2Cdc%3Ddemo1%2Cdc%3Dfreeipa%2Cdc%3Dorg).

Recently a contributor had issues with his password manager that was autocompleting some sensitive data in the admin console (despite the autocomplete attribute being set to off), triggering the auto save and persisting sensitive password in the config file, making the entire admin console unusable from chrome.

That was quite bad and there were 2 solutions:
1. remove the auto save feature from the admin console => that option was a no go
2. add that ugly new-password attribute => that's what we went for

In a perfect world, that fix would have only affected the admin console but because this is the same piece of form generation code, it is also used in the login form. That part of the code is the most hairy of the code base and it would take quite some time to get it right so as to provide a better fix.

Ultimately if you use Filestash in a professional setting, I'm happy to charge my consulting fee to do that work but it's not something I'm willing to do on my free time

**Comment by hughbris** [comment]
Thanks for the quick and detailed reply, I really appreciate it though it's not what I hoped to hear.

> In a perfect world, that fix would have only affected the admin console but because this is the same piece of form generation code, it is also used in the login form. That part of the code is the most hairy of the code base and it would take quite some time to get it right so as to provide a better fix.
> 

All frameworks have tradeoffs and I guess we've hit one here, unfortunately.

> Ultimately if you use Filestash in a professional setting, I'm happy to charge my consulting fee to do that work as it's not something I'm willing to do on my free time

I know where you are coming from and would love to be in a position to offer to compensate you. I'll try a couple of counter-arguments FWIW:

* I feel like this is a generic improvement for Filestash that opens it up to new use cases and users, some of whom will hopefully throw some money your way. I postulate this because I have two clients who are collecting sensitive information that they then need to access easily, but without storing any read credentials in the cloud. (The documents are posted up using write-only keys.) So I'm thinking this makes it a more attractive tool. Projection perhaps.
* I barely cover living expenses right now because I spend so much time getting this kind of thing right for clients. For the two I have in mind ATM, they are not strictly legally obligated to protect these personal documents but I feel it's the responsible course of action. So the point is I'm _not being professionally compensated for this particular protection_ I want to put in for the users of their sites. They would be happy for me to attach sensitive documents to emails. Semantics perhaps.

Don't interpret this as ungratefulness, but not having this capability is unfortunately a dealbreaker as my clients are unlikely to tolerate a "difficult" process. I honestly think Filestash is otherwise an amazing and attractive tool. I'm probably going to use it in preference to the official Backblaze web UI.

My next best option is probably Cyberduck, which will be difficult to support because I don't have a Windows box.

Keep up the great work! You've built something wonderful and I hope it pays off for you one day soon :)
