### ISSUE TITLE
Allow custom S3 endpoint

### ISSUE THREAD

**Issue by gnur** [mickael-kerjean/nuage#62]
It would be great to use custom S3 endpoints, to make it compatible with projects like https://github.com/minio/minio

**Comment by mickael-kerjean** [comment]
Great idea, I will look after it as soon as I have some free time. If you want to give it a try, pull requests are welcome as well.

**Comment by mickael-kerjean** [comment]
Looking at their documentation I'm just a bit confused, Minio claims it's compatible with S3 but it seems you have to replace the S3 SDK with their own? 

If we have to replace the Amazon SDK to use minio, I'm not very keen on **replacing** the official S3 SDK by something else (simply because Amazon is serious about its support and there might be subtile difference between both). However adding Minio as another backend would be a nice addition.

**Comment by gnur** [comment]
It is almost entirely API compatible with S3, most libraries work with both. Unless you use some specific features that are not available on minio. I've used minio with rclone and boto3 (python library) and it just worked. So if you allow changing the endpoint/region it will probably just work

**Comment by mickael-kerjean** [comment]
I'll give it a try.

**Comment by mickael-kerjean** [comment]
I'm just publishing here so that it serves as a knowledge base in the same time:

The AWS doc references a [endpoint thinghy](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#endpoint-property), the doc isn't really clear how it can be used (property of the object create from an instance of the AWS.S3?), some testing will have to be done.

**Comment by mickael-kerjean** [comment]
I got something that is starting to work. I'll push to master once it's 100% done.

**Comment by mickael-kerjean** [comment]
TADAHH! it should be working now :), once the build is done, I'll push it live as well.

Any change you could test it from your end once live (in a few minutes)?

**Comment by gnur** [comment]
I just built the docker container and it is working! Brilliant! Thanks :)

**Comment by mickael-kerjean** [comment]
Good to hear, feel free to reopen if there's something wrong :)

**Comment by zzinx58** [comment]
Hi, i was unable to setup local minio with filestash, could you help me out?
<img width="1349" alt="image" src="https://github.com/user-attachments/assets/75ce4fc2-c069-4963-9a1e-0a0d52354b05" />

**Comment by mickael-kerjean** [comment]
You are calling the endpoint from "http://localhost:9000" but from the Filestash container point of view, it probably can't see what you have in there unless you use the docker network as host
