### ISSUE TITLE
Todo states toggle only between TODO and DONE

### ISSUE THREAD

**Issue by Nebucatnetzer** [mickael-kerjean/nuage#74]
When you tap on a todo state it toggles only between TODO and DONE even when the initial state was something different like NEXT.

**Comment by mickael-kerjean** [comment]
I don't understand what you propose here, the current behavior is:
- 1 click: NEXT -> DONE 
- 2 clicks: NEXT -> DONE -> NEXT
- 3 clicks: NEXT -> DONE -> NEXT -> DONE

**Comment by Nebucatnetzer** [comment]
Somehow my comment by email didn't arrive here:

> That's not the behaviour I am seeing.
> 
>   * 1 click: NEXT -> DONE
>   * 2 clicks: NEXT -> DONE -> TODO
>   * 3 clicks: NEXT -> DONE -> TODO -> DONE

**Comment by mickael-kerjean** [comment]
That's not the behavior I'm observing from my end from the agenda or todo view. Can you provide more information about it?

**Comment by mickael-kerjean** [comment]
Hoo, maybe you're talking about clicking on the text ? You're right if you click on the text it doesn't come back to NEXT, it does so only from the agenda and todo view. 

The reason is the text is the state in the same way other sytems usually rely on a database to store their data. If you edit a row in a SQL database (aka the org document), you lose information as you got no way to know about the prior state. 

While implementing the feature of clicking on text for the todo state, I wanted to implement some sort of cycling first but then realise everyone use different keywords and it could take more clicks to find the proper keyword than just typing it directly which defeat the purpose of cycling in the first place.

**Comment by Nebucatnetzer** [comment]
I thought that might be the case :).
It's not really a problem to me just submitted it in case it was a bug.
